/**
 * Legal catalogue: the instruments PuraVidaGov's workflows rely on (Costa Rica) or point to (reference
 * countries). Data, not code. Per-workflow and per-step notes live next to each workflow definition in
 * apps/api/src/workflows and reference these ids. Research behind this file: docs/LEGAL.md and
 * docs/research/*.md — update both together.
 */
import type { LegalRef } from './types.js';

export const LEGAL_REFS: Record<string, LegalRef> = {
  // ------------------------------------------------------------------ Costa Rica
  'cr-8220': {
    id: 'cr-8220',
    jurisdiction: 'CR',
    name: 'Ley 8220, Protección al Ciudadano del Exceso de Requisitos y Trámites Administrativos (reformada por Ley 8990)',
    short: 'Ley 8220 arts. 2 y 8',
    year: 2002,
    url: 'https://www.meic.go.cr/documentos/ley-no-8220-ley-de-proteccion-al-ciudadano-del-exceso-de-requisitos-y-tramites-administativos-y-sus-reformas-publicada-en-el-diario-oficial-la-gaceta-no-49-alcance-22-del-11-03/',
    what: 'Art. 2: una misma institución no puede pedir dos veces lo que ya tiene, y para pasar datos a otra necesita el consentimiento de la persona. Art. 8: la institución que necesite un documento de otra «deberá coordinar con esta su obtención… para no solicitarla al administrado». Art. 7: silencio positivo. Es el «una sola vez» costarricense, vigilado solo por el MEIC y sin plataforma que lo haga posible.',
    whatEn: 'Art. 2: an institution may not ask twice for what it already holds, and needs the citizen\'s consent to pass data to another. Art. 8: an institution needing a document from another "must coordinate to obtain it… so as not to ask the citizen". Art. 7: positive silence. Costa Rica\'s once-only duty, overseen only by MEIC and without a platform to make it possible.',
  },
  'cr-8454': {
    id: 'cr-8454',
    jurisdiction: 'CR',
    name: 'Ley 8454, Ley de Certificados, Firmas Digitales y Documentos Electrónicos',
    short: 'Ley 8454',
    year: 2005,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=55666',
    what: 'Art. 9: la firma digital certificada tiene «el mismo valor y la eficacia probatoria» que la manuscrita. La ley faculta al Estado a usarla; la obligación de aceptarla viene solo de la Directriz 067-MICITT-H-MEIC (2014), que no ata a autónomas ni municipalidades.',
    whatEn: 'Art. 9: a certified digital signature has "the same value and evidentiary force" as a handwritten one. The law empowers the State to use it; the duty to accept it comes only from Directive 067-MICITT-H-MEIC (2014), which does not bind autonomous institutions or municipalities.',
  },
  'cr-8968': {
    id: 'cr-8968',
    jurisdiction: 'CR',
    name: 'Ley 8968, Protección de la Persona frente al Tratamiento de sus Datos Personales',
    short: 'Ley 8968',
    year: 2011,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=70975',
    what: 'Art. 5: consentimiento expreso, salvo orden judicial, datos públicos o «disposición constitucional o legal». Art. 14: una base de datos solo transfiere datos con autorización expresa del titular. El bus del demo es exactamente lo que esta ley permite hoy: consentimiento por intercambio y auditoría; para intercambios de oficio hace falta la «disposición legal». Proyecto de ley 23.097 (2022) en primer debate desde octubre de 2024.',
    whatEn: 'Art. 5: express consent, except by court order, public data or "constitutional or legal provision". Art. 14: a database transfers data only with the holder\'s express authorisation. The demo\'s bus is exactly what this law allows today: consent per exchange plus audit; ex-officio exchanges need the "legal provision". Bill 23.097 (2022) has sat at first debate since October 2024.',
  },
  'cr-9986': {
    id: 'cr-9986',
    jurisdiction: 'CR',
    name: 'Ley 9986, Ley General de Contratación Pública',
    short: 'Ley 9986 art. 16 (SICOP)',
    year: 2021,
    url: 'https://www.hacienda.go.cr/docs/LeyGeneraldeContratacionPublicaMayo2021.pdf',
    what: 'Art. 16: el sistema digital unificado «es único» para toda contratación con fondos públicos, municipalidades incluidas, y cualquier otro medio «implicará su nulidad absoluta». El único precedente costarricense de una plataforma nacional obligatoria por ley, bajo pena de nulidad.',
    whatEn: 'Art. 16: the unified digital system "is the only one" for any contracting with public funds, municipalities included, and any other means "entails absolute nullity". Costa Rica\'s only precedent of a national platform made mandatory by statute on pain of nullity.',
  },
  'cr-36550': {
    id: 'cr-36550',
    jurisdiction: 'CR',
    name: 'Decreto Ejecutivo 36550-MP-MIVAH-S-MEIC, Reglamento para el trámite de revisión de los planos para la construcción (plataforma APC del CFIA)',
    short: 'Decreto 36550 (APC)',
    year: 2011,
    url: 'https://www.bomberos.go.cr/revision-de-proyectos-constructivos-en-la-plataforma-apc/',
    what: 'Obliga a tramitar la revisión de planos en una sola plataforma digital (APC) donde INVU, Salud, Bomberos, AyA y el CFIA revisan un mismo juego de planos. En 2020, 70 de 82 municipalidades ya recibían el permiso 100 % digital por APC-M. La ventanilla única costarricense que ya funciona.',
    whatEn: 'Requires construction plan review through one digital platform (APC) where INVU, Health, Fire, Water and the CFIA review the same set of plans. By 2020, 70 of 82 municipalities received the permit fully digitally through APC-M. Costa Rica\'s working one-stop window.',
  },
  'cr-833': {
    id: 'cr-833',
    jurisdiction: 'CR',
    name: 'Ley 833, Ley de Construcciones',
    short: 'Ley 833 art. 74 / Ley 4240 art. 70',
    year: 1949,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=37590',
    what: 'La licencia municipal de construcción (Ley 833 art. 74) y el impuesto de hasta el 1 % del valor de la obra (Ley 4240 de Planificación Urbana, art. 70) son municipales; el uso de suelo también. Cada municipalidad decide si se conecta a APC-M.',
    whatEn: 'The municipal building licence (Ley 833 art. 74) and the tax of up to 1 % of the declared value (Ley 4240 on Urban Planning, art. 70) are municipal; so is land use. Each municipality decides whether to connect to APC-M.',
  },
  'cr-7794': {
    id: 'cr-7794',
    jurisdiction: 'CR',
    name: 'Ley 7794, Código Municipal',
    short: 'Código Municipal art. 88',
    year: 1998,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=40197',
    what: 'Art. 88 (reformado por Ley 10421, 2023): la licencia para actividades lucrativas es municipal y cada cantón la cobra con su propia ley de patentes (p. ej. Ley 5694 para San José). 84 municipalidades, 84 formularios; la Constitución (art. 170) protege su autonomía, así que solo una ley las obliga.',
    whatEn: 'Art. 88 (amended by Ley 10421, 2023): the business licence is municipal and each canton charges it under its own patente law (e.g. Ley 5694 for San José). 84 municipalities, 84 forms; the Constitution (art. 170) protects their autonomy, so only a statute can bind them.',
  },
  'cr-5395': {
    id: 'cr-5395',
    jurisdiction: 'CR',
    name: 'Ley 5395, Ley General de Salud, y Reglamento General para Autorizaciones y Permisos Sanitarios de Funcionamiento (Decreto 43432-S)',
    short: 'Ley 5395 / Decreto 43432-S',
    year: 1973,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=6581',
    what: 'El Permiso Sanitario de Funcionamiento (PSF) se tramita ante el Área Rectora de Salud; con el Decreto 43432-S la declaración jurada es en línea y el permiso dura cinco años. Sigue siendo una ventanilla aparte que pide la patente y el recibo que otra institución ya tiene.',
    whatEn: 'The sanitary operating permit (PSF) is processed at the local Health Area; under Decree 43432-S the sworn declaration is online and the permit lasts five years. It remains a separate window asking for the licence and receipt another institution already holds.',
  },
  'cr-3504': {
    id: 'cr-3504',
    jurisdiction: 'CR',
    name: 'Ley 3504, Ley Orgánica del Tribunal Supremo de Elecciones y del Registro Civil',
    short: 'Ley 3504',
    year: 1965,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=33236',
    what: 'El Registro Civil inscribe nacimientos; desde 2016 los hospitales los declaran en línea al TSE y la inscripción es el mismo día (≈98 % de los partos son hospitalarios). El cambio de domicilio electoral, en cambio, solo está en línea para quienes viven en el exterior.',
    whatEn: 'The Civil Registry records births; since 2016 hospitals declare them online to the TSE and registration is same-day (≈98 % of births are in hospital). The electoral address change, by contrast, is online only for citizens living abroad.',
  },
  'cr-17': {
    id: 'cr-17',
    jurisdiction: 'CR',
    name: 'Ley 17, Ley Constitutiva de la Caja Costarricense de Seguro Social',
    short: 'Ley 17 (CCSS)',
    year: 1943,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=2126',
    what: 'Aseguramiento obligatorio de trabajadores y patronos; la inscripción patronal y la pensión IVM (desde julio de 2025) se hacen en la Oficina Virtual. Asegurar a un recién nacido como beneficiario sigue siendo a solicitud de la familia, en el EBAIS o en línea, en unos ocho días: la CCSS es autónoma y nadie le avisa del nacimiento.',
    whatEn: 'Mandatory insurance of workers and employers; employer registration and the IVM pension (since July 2025) are done in the Oficina Virtual. Insuring a newborn as a dependant is still on the family\'s request, at the clinic or online, in about eight days: the CCSS is autonomous and nobody tells it about the birth.',
  },
  'cr-7983': {
    id: 'cr-7983',
    jurisdiction: 'CR',
    name: 'Ley 7983, Ley de Protección al Trabajador',
    short: 'Ley 7983',
    year: 2000,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=43868',
    what: 'ROP y Fondo de Capitalización Laboral (FCL, art. 3) administrados por operadoras bajo SUPEN; el FCL se paga en 15 días al cesar la relación laboral (art. 6), pero el trabajador debe probar el despido con papeles. No existe seguro de desempleo.',
    whatEn: 'ROP and the labour capitalisation fund (FCL, art. 3) run by operators under SUPEN; the FCL is paid within 15 days of termination (art. 6), but the worker must prove dismissal with paperwork. There is no unemployment insurance.',
  },
  'cr-9078': {
    id: 'cr-9078',
    jurisdiction: 'CR',
    name: 'Ley 9078, Ley de Tránsito por Vías Públicas Terrestres y Seguridad Vial',
    short: 'Ley 9078',
    year: 2012,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=73504',
    what: 'El dictamen médico ya es digital (SEDIMEC), pero la renovación sigue siendo presencial en 42 sucursales del BCR y 13 sedes del MOPT; el MOPT licitó en 2026 la licencia digital y el examen teórico en línea.',
    whatEn: 'The medical certificate is already digital (SEDIMEC), but renewal remains in person at 42 BCR branches and 13 MOPT offices; the MOPT tendered the digital licence and online theory test in 2026.',
  },
  'cr-crear-empresa': {
    id: 'cr-crear-empresa',
    jurisdiction: 'CR',
    name: 'Plataforma Crear Empresa (MEIC / Registro Nacional) y Ventanilla Única de Inversión (PROCOMER)',
    short: 'Crear Empresa / VUI',
    year: 2012,
    url: 'https://www.crearempresa.go.cr',
    what: 'Crear Empresa constituye la sociedad en línea con firma digital y puede avisar, si la institución adhirió, a Tributación, CCSS, Salud, SETENA, SENASA, INS y municipalidades. La VUI (PROCOMER, 2018) encadena más de 40 trámites de 19 instituciones y 54 municipalidades. Ambas son voluntarias para las instituciones: por eso no cubren el país.',
    whatEn: 'Crear Empresa forms the company online with a digital signature and can notify, where the institution opted in, the tax authority, CCSS, Health, SETENA, SENASA, INS and municipalities. The VUI (PROCOMER, 2018) chains over 40 procedures across 19 institutions and 54 municipalities. Both are voluntary for institutions, which is why they do not cover the country.',
  },
  'cr-idc': {
    id: 'cr-idc',
    jurisdiction: 'CR',
    name: 'Identidad Digital Costarricense (IDC) del TSE: Reglamento del servicio de identificación digital (2025) y resolución 1120-E7-2026',
    short: 'IDC (TSE, 2025)',
    year: 2025,
    url: 'https://www.tse.go.cr/idc/',
    what: 'La cédula en el teléfono, emitida por el TSE desde el 9 de septiembre de 2025 con la misma validez que la física; su aceptación obligatoria se fijó por resolución del TSE para el 1 de enero de 2027. Es un reglamento del TSE, no una ley, y es una credencial, no un inicio de sesión único para los servicios del Estado.',
    whatEn: 'The cédula on the phone, issued by the TSE since 9 September 2025 with the same validity as the physical card; mandatory acceptance was set by TSE resolution for 1 January 2027. A TSE regulation, not a statute, and a credential rather than a single sign-on for State services.',
  },
  'cr-9943': {
    id: 'cr-9943',
    jurisdiction: 'CR',
    name: 'Ley 9943, Creación de la Agencia Nacional de Gobierno Digital (ANGD), y su reglamento (Decreto 44636-MP-MICITT, 2024)',
    short: 'Ley 9943 (ANGD)',
    year: 2021,
    url: 'https://www.imprentanacional.go.cr/pub/2021/09/29/ALCA195_29_09_2021.pdf',
    what: 'Art. 2: derecho de la persona a relacionarse digitalmente con el Estado; art. 5: la ANGD debe «implementar mecanismos de intercambio de información, identidad digital e integración de los sistemas». Sin regla de «una sola vez», sin base legal de intercambio ni sanción; la agencia opera desde septiembre de 2025 con financiamiento temporal (art. 7).',
    whatEn: 'Art. 2: the citizen\'s right to deal digitally with the State; art. 5: the ANGD must "implement mechanisms for information exchange, digital identity and systems integration". No once-only rule, no legal basis for exchange, no sanction; the agency has operated since September 2025 on temporary funding (art. 7).',
  },
  'cr-conecta': {
    id: 'cr-conecta',
    jurisdiction: 'CR',
    name: 'Modelo de Interoperabilidad (MICITT, 2025) y proyecto Conecta CRI/003 (MICITT–ANGD–LuxDev, 2026): X-Road como plataforma nacional',
    short: 'Conecta / X-Road CR (2026)',
    year: 2026,
    url: 'https://www.micitt.go.cr/el-sector-informa/costa-rica-acelera-su-transformacion-digital-con-el-lanzamiento-del-proyecto',
    what: 'El Gobierno ya eligió X-Road como plataforma nacional de interoperabilidad y lanzó Conecta en marzo de 2026 con 30 instituciones; el primer piloto (salud) corrió en junio de 2026. El propio informe técnico del MICITT señala como riesgo la «falta de marco legal vinculante que obligue a las instituciones autónomas y municipalidades a interoperar». Es exactamente lo que este demo simula.',
    whatEn: 'The Government has already chosen X-Road as the national interoperability platform and launched Conecta in March 2026 with 30 institutions; the first pilot (health) ran in June 2026. MICITT\'s own technical report flags as a risk the "lack of a binding legal framework obliging autonomous institutions and municipalities to interoperate". Exactly what this demo simulates.',
  },
  // ------------------------------------------------------------------ Estonia
  'ee-pia': {
    id: 'ee-pia',
    jurisdiction: 'EE',
    name: 'Public Information Act (Avaliku teabe seadus), capítulo 5¹ «Bases de datos» (2008): «una sola vez», registros base y X-Road obligatorio',
    short: 'Estonia, Public Information Act §43¹–43⁹',
    year: 2000,
    url: 'https://www.riigiteataja.ee/en/eli/522122014002/consolide/current',
    what: '§43¹(3): «la recolección de datos se basará en el principio de una sola solicitud». §43³(2): prohibido crear bases separadas para los mismos datos. §43⁶: los «datos básicos» de una base son la fuente obligatoria para las demás (registros base). §43⁹(3): usar la capa de intercambio (X-Road) y el catálogo RIHA «es obligatorio para todas las bases de datos estatales y municipales».',
    whatEn: '§43¹(3): "collection of data shall be based on the one-request-only principle". §43³(2): separate databases for the same data are prohibited. §43⁶: a database\'s "basic data" is the mandatory source for all others (base registries). §43⁹(3): using the exchange layer (X-Road) and the RIHA catalogue "is mandatory for all state and local government databases".',
  },
  'ee-xroad': {
    id: 'ee-xroad',
    jurisdiction: 'EE',
    name: 'Reglamento del Gobierno n.º 105 «Capa de intercambio de datos de los sistemas de información» (X-Road), dictado con base en §43⁹ de la Public Information Act',
    short: 'Estonia, reglamento X-Road 105/2016',
    year: 2016,
    url: 'https://www.riigiteataja.ee/akt/127092016004',
    what: 'Define X-Road como «la infraestructura técnica… que permite el intercambio de datos seguro y verificable», nombra a RIA como operador, regula la adhesión por convenio y exige el registro sellado de cada mensaje (query log) y auditorías cada cuatro años. Unas 1 500 organizaciones y 600 millones de consultas al año. Es lo que el bus del demo imita.',
    whatEn: 'Defines X-Road as "the technical infrastructure… enabling secure and verifiable data exchange", names RIA as operator, regulates accession by agreement and requires the stamped log of every message (query log) and audits every four years. About 1,500 organisations and 600 million queries a year. What the demo\'s bus imitates.',
  },
  'ee-idcard': {
    id: 'ee-idcard',
    jurisdiction: 'EE',
    name: 'Identity Documents Act (Isikut tõendavate dokumentide seadus): cédula con certificados obligatoria',
    short: 'Estonia, Identity Documents Act',
    year: 1999,
    url: 'https://www.riigiteataja.ee/en/eli/ee/504112013003/consolide',
    what: '§5(1): «todo ciudadano estonio residente en Estonia deberá tener una cédula de identidad» (desde los 15 años); §9⁴: el emisor incorpora en ella un certificado de autenticación y otro de firma. Con la equivalencia de la firma digital (2000), una sola identidad sirve para todo el Estado.',
    whatEn: '§5(1): "an Estonian citizen residing in Estonia shall hold an identity card" (from age 15); §9⁴: the issuer embeds an authentication and a signing certificate in it. With signature equivalence (2000), one identity serves the whole State.',
  },
  // ------------------------------------------------------------------ Singapore
  'sg-psga': {
    id: 'sg-psga',
    jurisdiction: 'SG',
    name: 'Public Sector (Governance) Act 2018, Parte 4 «Data sharing» (arts. 6–8)',
    short: 'Singapur, PSGA 2018 arts. 6–8',
    year: 2018,
    url: 'https://sso.agc.gov.sg/Act/PSGA2018',
    what: 'Art. 6: un ministro puede ordenar a una agencia compartir datos con otra para fines de interés público; arts. 7 y 8: divulgación no autorizada o reidentificación son delitos (multa y hasta dos años de prisión). Base legal del intercambio por instrucción, no por consentimiento, sobre la que corren MyInfo y LifeSG.',
    whatEn: 'S. 6: a minister may direct an agency to share data with another for public-interest purposes; ss. 7–8: unauthorised disclosure or re-identification are offences (fine and up to two years\' imprisonment). The legal basis for sharing by direction rather than consent, on which MyInfo and LifeSG run.',
  },
  'sg-myinfo': {
    id: 'sg-myinfo',
    jurisdiction: 'SG',
    name: 'Singpass / MyInfo («Tell us once») y LifeSG (servicios por momentos de vida)',
    short: 'Singapur, MyInfo y LifeSG',
    year: 2016,
    url: 'https://www.singpass.gov.sg/main/individuals/myinfo/',
    what: 'Singpass (2003; más de 5 millones de usuarios y 2 700 servicios), MyInfo (2016: «díganos una vez», prellenado con datos verificados por el Estado y pantalla de consentimiento por dato) y LifeSG (2020: servicios por momentos de vida). Desde noviembre de 2021 todas las agencias aceptan la cédula digital por decisión de gobierno; el 99 % de las transacciones son digitales. No hay ley específica: es política ejecutiva con metas medidas.',
    whatEn: 'Singpass (2003; over 5 million users and 2,700 services), MyInfo (2016: "tell us once", pre-fill with government-verified data and a per-item consent screen) and LifeSG (2020: services by life moments). Since November 2021 all agencies accept the digital ID by government decision; 99 % of transactions are digital. No specific statute: executive policy with measured targets.',
  },
  // ------------------------------------------------------------------ EU and Latin America
  'eu-sdg': {
    id: 'eu-sdg',
    jurisdiction: 'EU',
    name: 'Reglamento (UE) 2018/1724, Pasarela Digital Única, art. 14: sistema técnico «solo una vez» (OOTS, operativo desde diciembre de 2023)',
    short: 'UE, Reglamento 2018/1724 art. 14',
    year: 2018,
    url: 'https://eur-lex.europa.eu/eli/reg/2018/1724/oj',
    what: 'Art. 14: sistema técnico de intercambio automático de evidencias entre autoridades de distintos Estados, «a petición expresa del usuario» y con vista previa de lo que se envía. Operativo desde el 12 de diciembre de 2023. La Comisión lo justificó con ahorros estimados de hasta 5 000 millones de euros al año.',
    whatEn: 'Art. 14: a technical system for automated exchange of evidence between authorities of different States, "at the explicit request of the user" and with a preview of what is sent. Live since 12 December 2023. The Commission justified it with estimated savings of up to €5 billion a year.',
  },
  'eu-eidas2': {
    id: 'eu-eidas2',
    jurisdiction: 'EU',
    name: 'Reglamento (UE) 2024/1183 (eIDAS 2): billetera europea de identidad digital',
    short: 'UE, eIDAS 2 (2024)',
    year: 2024,
    url: 'https://eur-lex.europa.eu/eli/reg/2024/1183/oj',
    what: 'Art. 5a: cada Estado debe ofrecer una billetera de identidad digital gratuita, con registro de transacciones visible para la persona. Art. 5f: las entidades públicas y los sectores privados regulados (banca, telecomunicaciones, grandes plataformas) deben aceptarla. Lo que la IDC costarricense necesitaría para ser universal por ley y no por resolución.',
    whatEn: 'Art. 5a: every State must offer a free digital identity wallet with a transaction log visible to the person. Art. 5f: public bodies and regulated private sectors (banking, telecoms, large platforms) must accept it. What Costa Rica\'s IDC would need to become universal by statute rather than by resolution.',
  },
  'br-14129': {
    id: 'br-14129',
    jurisdiction: 'BR',
    name: 'Lei 14.129/2021, Governo Digital (Brasil): principio de no exigir datos que el Estado ya posee, plataforma gov.br',
    short: 'Brasil, Lei 14.129/2021',
    year: 2021,
    url: 'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14129.htm',
    what: 'Art. 3 XIII: «prohibición de exigir prueba de un hecho ya comprobado» con un documento válido; art. 24 IV: eliminar «inclusive por medio de la interoperabilidad de datos» las exigencias innecesarias; arts. 38–39: interoperabilidad de bases con clave CPF. gov.br supera los 170 millones de cuentas y 12 000 servicios.',
    whatEn: 'Art. 3 XIII: "prohibition on demanding proof of a fact already proven" by a valid document; art. 24 IV: eliminate unnecessary requirements "including through data interoperability"; arts. 38–39: database interoperability keyed on the CPF. gov.br exceeds 170 million accounts and 12,000 services.',
  },
  'uy-18600': {
    id: 'uy-18600',
    jurisdiction: 'UY',
    name: 'Uruguay, Ley 18.719 arts. 157–160 (deber de intercambio e interoperabilidad, AGESIC como autoridad) y Decreto 178/013 (Plataforma de Interoperabilidad)',
    short: 'Uruguay, Ley 18.719 arts. 157–160',
    year: 2010,
    url: 'https://www.impo.com.uy/bases/leyes/18719-2010/157',
    what: 'Art. 157: las entidades «deberán adoptar las medidas necesarias… para promover el intercambio de información»; art. 159: con consentimiento informado; art. 160: AGESIC fija estándares, lleva el registro de acuerdos de interoperabilidad y resuelve disputas de forma vinculante en 45 días. Uruguay es el primero de América Latina en el índice de gobierno digital de la ONU (puesto 25 de 193 en 2024; Costa Rica, 61).',
    whatEn: 'Art. 157: entities "shall adopt the measures needed… to promote information exchange"; art. 159: with informed consent; art. 160: AGESIC sets standards, keeps the register of interoperability agreements and settles disputes bindingly within 45 days. Uruguay leads Latin America in the UN e-government index (25th of 193 in 2024; Costa Rica 61st).',
  },
};

export const JURISDICTION_LABELS: Record<string, { es: string; en: string; flag: string }> = {
  CR: { es: 'Costa Rica', en: 'Costa Rica', flag: '🇨🇷' },
  EE: { es: 'Estonia', en: 'Estonia', flag: '🇪🇪' },
  SG: { es: 'Singapur', en: 'Singapore', flag: '🇸🇬' },
  EU: { es: 'Unión Europea', en: 'European Union', flag: '🇪🇺' },
  UY: { es: 'Uruguay', en: 'Uruguay', flag: '🇺🇾' },
  BR: { es: 'Brasil', en: 'Brazil', flag: '🇧🇷' },
};

export function legalRef(id: string): LegalRef {
  const ref = LEGAL_REFS[id];
  if (!ref) throw new Error(`Unknown legal ref: ${id}`);
  return ref;
}
