/**
 * Legal catalogue: the instruments PuraVidaGov's workflows rely on (Costa Rica) or point to (reference
 * countries). Data, not code. Per-workflow and per-step notes live next to each workflow definition in
 * apps/api/src/workflows and reference these ids. Research behind this file: docs/LEGAL.md and
 * docs/research/*.md — update both together.
 */
import type { LegalRef } from './types.js';

export const LEGAL_REFS: Record<string, LegalRef> = {
  // ------------------------------------------------------------------ Costa Rica
  'cr-8220': {
    id: 'cr-8220',
    jurisdiction: 'CR',
    name: 'Ley 8220, Protección al Ciudadano del Exceso de Requisitos y Trámites Administrativos (reformada por Ley 8990)',
    short: 'Ley 8220 art. 2',
    year: 2002,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=48134',
    what: 'Ya prohíbe pedir al ciudadano información o documentos que otra institución del Estado posee («presentación única»), fija plazos y el silencio positivo. Es el «una sola vez» costarricense, sin la plataforma que lo haga cumplir.',
    whatEn: 'Already forbids asking citizens for information or documents another State entity holds (single submission), sets deadlines and positive silence. It is Costa Rica\'s once-only duty, without the platform to enforce it.',
  },
  'cr-8454': {
    id: 'cr-8454',
    jurisdiction: 'CR',
    name: 'Ley 8454, Ley de Certificados, Firmas Digitales y Documentos Electrónicos',
    short: 'Ley 8454',
    year: 2005,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=55666',
    what: 'Da a la firma digital certificada la misma validez que la manuscrita y obliga al Estado a aceptar documentos electrónicos. La identidad digital del demo existe en derecho desde 2005.',
    whatEn: 'Gives certified digital signatures the same validity as handwritten ones and obliges the State to accept electronic documents. The demo\'s digital identity has existed in law since 2005.',
  },
  'cr-8968': {
    id: 'cr-8968',
    jurisdiction: 'CR',
    name: 'Ley 8968, Protección de la Persona frente al Tratamiento de sus Datos Personales',
    short: 'Ley 8968',
    year: 2011,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=70975',
    what: 'Consentimiento informado, finalidad y transferencia de datos. El bus del demo cumple su espíritu: cada intercambio tiene consentimiento, finalidad y queda auditado para la persona.',
    whatEn: 'Informed consent, purpose limitation and data transfers. The demo\'s bus follows its spirit: every exchange carries consent, a purpose and is audited for the citizen.',
  },
  'cr-9986': {
    id: 'cr-9986',
    jurisdiction: 'CR',
    name: 'Ley 9986, Ley General de Contratación Pública',
    short: 'Ley 9986 (SICOP)',
    year: 2021,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=94627',
    what: 'Hace obligatorio el sistema digital unificado de compras (SICOP) para toda la Administración. Prueba que Costa Rica sí sabe imponer una plataforma única por ley.',
    whatEn: 'Makes the unified digital procurement system (SICOP) mandatory for the whole public administration. Proof that Costa Rica can mandate a single platform by law.',
  },
  'cr-36550': {
    id: 'cr-36550',
    jurisdiction: 'CR',
    name: 'Decreto Ejecutivo 36550-MP-MIVAH-S-MEIC, Reglamento para el trámite de revisión de los planos para la construcción (plataforma APC del CFIA)',
    short: 'Decreto 36550 (APC)',
    year: 2011,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=70366',
    what: 'Obliga a tramitar la revisión de planos en una sola plataforma digital (APC) donde Salud, Bomberos, AyA e INVU revisan en paralelo. Es el ejemplo costarricense de ventanilla única que ya funciona.',
    whatEn: 'Requires construction plan review through one digital platform (APC) where Health, Fire, Water and Housing review in parallel. Costa Rica\'s working example of a one-stop window.',
  },
  'cr-833': {
    id: 'cr-833',
    jurisdiction: 'CR',
    name: 'Ley 833, Ley de Construcciones',
    short: 'Ley 833',
    year: 1949,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=37590',
    what: 'El permiso municipal de construcción y el impuesto del 1 % sobre el valor de la obra siguen siendo municipales. Cada municipalidad tiene su propio sistema.',
    whatEn: 'The municipal building permit and the 1 % tax on the declared value remain municipal. Each municipality runs its own system.',
  },
  'cr-7794': {
    id: 'cr-7794',
    jurisdiction: 'CR',
    name: 'Ley 7794, Código Municipal',
    short: 'Código Municipal art. 88',
    year: 1998,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=40197',
    what: 'La licencia (patente) para actividades lucrativas es municipal y cada cantón la regula con su propia ley de patentes. 84 municipalidades, 84 ventanillas.',
    whatEn: 'The business licence (patente) is municipal and each canton regulates it with its own patente law. 84 municipalities, 84 windows.',
  },
  'cr-5395': {
    id: 'cr-5395',
    jurisdiction: 'CR',
    name: 'Ley 5395, Ley General de Salud, y Reglamento General para Autorizaciones y Permisos Sanitarios de Funcionamiento (Decreto 39472-S)',
    short: 'Ley 5395 / Decreto 39472-S',
    year: 1973,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=6581',
    what: 'El Permiso Sanitario de Funcionamiento (PSF) se tramita ante el Área Rectora de Salud; para riesgo bajo es declaración jurada. Hoy se pide en papel o por correo, con copia de la patente y del recibo.',
    whatEn: 'The sanitary operating permit (PSF) is processed at the local Health Area; low-risk activities use a sworn declaration. Today it is requested on paper or by e-mail, with copies of the patente and the receipt.',
  },
  'cr-3504': {
    id: 'cr-3504',
    jurisdiction: 'CR',
    name: 'Ley 3504, Ley Orgánica del Tribunal Supremo de Elecciones y del Registro Civil',
    short: 'Ley 3504',
    year: 1965,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=33236',
    what: 'El Registro Civil inscribe nacimientos; los hospitales de la CCSS ya declaran los nacimientos electrónicamente al TSE. El cambio de domicilio electoral también está en línea.',
    whatEn: 'The Civil Registry records births; CCSS hospitals already declare births electronically to the TSE. Electoral address changes are also online.',
  },
  'cr-17': {
    id: 'cr-17',
    jurisdiction: 'CR',
    name: 'Ley 17, Ley Constitutiva de la Caja Costarricense de Seguro Social',
    short: 'Ley 17 (CCSS)',
    year: 1943,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=2126',
    what: 'Aseguramiento obligatorio de trabajadores y patronos; la inscripción patronal se hace hoy en la Oficina Virtual (SICERE). El aseguramiento de dependientes exige presentarse con documentos.',
    whatEn: 'Mandatory insurance of workers and employers; employer registration is done today in the Oficina Virtual (SICERE). Insuring dependants still requires showing up with documents.',
  },
  'cr-7983': {
    id: 'cr-7983',
    jurisdiction: 'CR',
    name: 'Ley 7983, Ley de Protección al Trabajador',
    short: 'Ley 7983',
    year: 2000,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=43868',
    what: 'Régimen Obligatorio de Pensiones (ROP) y Fondo de Capitalización Laboral (FCL) administrados por operadoras bajo SUPEN; la pensión IVM la resuelve la CCSS con su historial de cuotas.',
    whatEn: 'Mandatory pension (ROP) and labour capitalisation fund (FCL) run by operators under SUPEN; the IVM pension is decided by the CCSS from its own contribution history.',
  },
  'cr-9078': {
    id: 'cr-9078',
    jurisdiction: 'CR',
    name: 'Ley 9078, Ley de Tránsito por Vías Públicas Terrestres y Seguridad Vial',
    short: 'Ley 9078',
    year: 2012,
    url: 'http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?nValor1=1&nValor2=73504',
    what: 'La licencia de conducir la emite COSEVI; la renovación exige dictamen médico y pago, con cita presencial para la fotografía.',
    whatEn: 'Driving licences are issued by COSEVI; renewal needs a medical certificate and payment, with an in-person appointment for the photo.',
  },
  'cr-crear-empresa': {
    id: 'cr-crear-empresa',
    jurisdiction: 'CR',
    name: 'Plataforma Crear Empresa (MEIC / Registro Nacional) y Ventanilla Única de Inversión (PROCOMER)',
    short: 'Crear Empresa / VUI',
    year: 2012,
    url: 'https://www.crearempresa.go.cr',
    what: 'Permite constituir una sociedad en línea mediante notario y obtener la cédula jurídica del Registro Nacional; la VUI encadena algunos permisos. Ninguna llega a la CCSS ni a las 84 patentes municipales.',
    whatEn: 'Allows forming a company online through a notary and obtaining the legal id from the Registro Nacional; the VUI chains some permits. Neither reaches the CCSS or the 84 municipal patentes.',
  },
  'cr-pase-digital': {
    id: 'cr-pase-digital',
    jurisdiction: 'CR',
    name: 'Pase Digital (billetera de identidad digital del Estado)',
    short: 'Pase Digital',
    year: 2024,
    url: 'https://pasedigital.go.cr',
    what: 'Identidad digital con la cédula del TSE en el teléfono. Es una plataforma, no una ley: ninguna norma obliga a todas las instituciones a aceptarla.',
    whatEn: 'Digital identity with the TSE cédula on the phone. A platform, not a law: no rule obliges every institution to accept it.',
  },
  // ------------------------------------------------------------------ Estonia
  'ee-pia': {
    id: 'ee-pia',
    jurisdiction: 'EE',
    name: 'Public Information Act (Avaliku teabe seadus), capítulo 5¹ «Bases de datos» — X-Road y principio «una sola vez»',
    short: 'Estonia, Public Information Act §43¹–43⁹',
    year: 2000,
    url: 'https://www.riigiteataja.ee/en/eli/ee/518012016001/consolide',
    what: 'Toda base de datos estatal debe registrarse, intercambiar datos por la capa X-Road y no puede recolectar datos que ya existan en otra base. El «una sola vez» con fuerza de ley y plataforma obligatoria.',
    whatEn: 'Every state database must be registered, exchange data through the X-Road layer and may not collect data that already exists in another database. Once-only with the force of law and a mandatory platform.',
  },
  'ee-xroad': {
    id: 'ee-xroad',
    jurisdiction: 'EE',
    name: 'Reglamento del Gobierno «Capa de intercambio de datos de los sistemas de información» (X-Road)',
    short: 'Estonia, reglamento X-Road',
    year: 2016,
    url: 'https://www.riigiteataja.ee/en/eli/ee/VV/reg/518122019001/consolide',
    what: 'Define técnica y jurídicamente la capa de intercambio: servidores de seguridad, firma y sellado de cada mensaje, registro de cada consulta. Es lo que el bus del demo imita.',
    whatEn: 'Defines the exchange layer technically and legally: security servers, signing and time-stamping of every message, logging of every query. What the demo\'s bus imitates.',
  },
  'ee-idcard': {
    id: 'ee-idcard',
    jurisdiction: 'EE',
    name: 'Identity Documents Act (Isikut tõendavate dokumentide seadus): cédula con certificados obligatoria',
    short: 'Estonia, Identity Documents Act',
    year: 1999,
    url: 'https://www.riigiteataja.ee/en/eli/ee/504112013003/consolide',
    what: 'La cédula electrónica con certificados de autenticación y firma es obligatoria para todo residente; toda institución debe aceptarla.',
    whatEn: 'The electronic ID card with authentication and signature certificates is mandatory for every resident; every institution must accept it.',
  },
  // ------------------------------------------------------------------ Singapore
  'sg-psga': {
    id: 'sg-psga',
    jurisdiction: 'SG',
    name: 'Public Sector (Governance) Act 2018: intercambio de datos entre agencias y sanciones por mal uso',
    short: 'Singapur, PSGA 2018',
    year: 2018,
    url: 'https://sso.agc.gov.sg/Act/PSGA2018',
    what: 'Autoriza a las agencias a compartir datos entre sí para fines públicos y castiga penalmente su uso indebido. Es la base de MyInfo y de LifeSG.',
    whatEn: 'Authorises agencies to share data with one another for public purposes and criminalises misuse. The basis of MyInfo and LifeSG.',
  },
  'sg-myinfo': {
    id: 'sg-myinfo',
    jurisdiction: 'SG',
    name: 'Singpass / MyInfo («Tell us once») y LifeSG (servicios por momentos de vida)',
    short: 'Singapur, MyInfo y LifeSG',
    year: 2016,
    url: 'https://www.singpass.gov.sg/main/individuals/myinfo/',
    what: 'Una identidad digital nacional, un perfil con los datos que el Estado ya tiene, y una app organizada por eventos de vida («tuve un hijo») en vez de por ministerios.',
    whatEn: 'One national digital identity, one profile with the data the State already holds, and an app organised by life events instead of by ministries.',
  },
  // ------------------------------------------------------------------ EU and Latin America
  'eu-sdg': {
    id: 'eu-sdg',
    jurisdiction: 'EU',
    name: 'Reglamento (UE) 2018/1724, Pasarela Digital Única, art. 14: sistema técnico «solo una vez» (OOTS, operativo desde diciembre de 2023)',
    short: 'UE, Reglamento 2018/1724 art. 14',
    year: 2018,
    url: 'https://eur-lex.europa.eu/eli/reg/2018/1724/oj',
    what: 'Obliga a los 27 Estados a intercambiar evidencias entre sí a petición del ciudadano, con vista previa y consentimiento. El «una sola vez» transfronterizo.',
    whatEn: 'Obliges the 27 Member States to exchange evidence with one another at the citizen\'s request, with preview and consent. Cross-border once-only.',
  },
  'eu-eidas2': {
    id: 'eu-eidas2',
    jurisdiction: 'EU',
    name: 'Reglamento (UE) 2024/1183 (eIDAS 2): billetera europea de identidad digital',
    short: 'UE, eIDAS 2 (2024)',
    year: 2024,
    url: 'https://eur-lex.europa.eu/eli/reg/2024/1183/oj',
    what: 'Cada Estado debe ofrecer una billetera de identidad digital y los servicios públicos y sectores regulados deben aceptarla. Lo que Pase Digital necesitaría para ser universal.',
    whatEn: 'Every Member State must offer a digital identity wallet and public services and regulated sectors must accept it. What Pase Digital would need to become universal.',
  },
  'br-14129': {
    id: 'br-14129',
    jurisdiction: 'BR',
    name: 'Lei 14.129/2021, Governo Digital (Brasil): principio de no exigir datos que el Estado ya posee, plataforma gov.br',
    short: 'Brasil, Lei 14.129/2021',
    year: 2021,
    url: 'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14129.htm',
    what: 'Ejemplo latinoamericano reciente: ley marco que fija el «una sola vez», la interoperabilidad y la identidad digital única (gov.br) para todos los niveles de gobierno.',
    whatEn: 'Recent Latin American example: framework law fixing once-only, interoperability and a single digital identity (gov.br) for all levels of government.',
  },
  'uy-18600': {
    id: 'uy-18600',
    jurisdiction: 'UY',
    name: 'Uruguay, Ley 18.600 de documento y firma electrónica, y AGESIC como autoridad de gobierno digital con plataforma de interoperabilidad',
    short: 'Uruguay, Ley 18.600 / AGESIC',
    year: 2009,
    url: 'https://www.impo.com.uy/bases/leyes/18600-2009',
    what: 'El país de la región mejor ubicado en el índice de gobierno digital de la ONU lo logró con una agencia central con presupuesto y una plataforma de interoperabilidad obligatoria.',
    whatEn: 'The region\'s best-ranked country in the UN e-government index got there with a central agency with budget power and a mandatory interoperability platform.',
  },
};

export const JURISDICTION_LABELS: Record<string, { es: string; en: string; flag: string }> = {
  CR: { es: 'Costa Rica', en: 'Costa Rica', flag: '🇨🇷' },
  EE: { es: 'Estonia', en: 'Estonia', flag: '🇪🇪' },
  SG: { es: 'Singapur', en: 'Singapore', flag: '🇸🇬' },
  EU: { es: 'Unión Europea', en: 'European Union', flag: '🇪🇺' },
  UY: { es: 'Uruguay', en: 'Uruguay', flag: '🇺🇾' },
  BR: { es: 'Brasil', en: 'Brazil', flag: '🇧🇷' },
};

export function legalRef(id: string): LegalRef {
  const ref = LEGAL_REFS[id];
  if (!ref) throw new Error(`Unknown legal ref: ${id}`);
  return ref;
}
